name: Create a Github release
on:
  workflow_dispatch:
    inputs:
      commit_sha:
          description: 'The release commit'     
          required: true
env:
  GIT_USER_NAME: amplify-android-dev+ghops
  GIT_USER_EMAIL: amplify-android-dev+ghops@amazon.com
jobs:      
  get_commit_sha:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.determine_commit_source.outputs.commit_sha }}
    steps:
      - id: determine_commit_source
        run: |
          if [[ "${{ github.event_name }}" = "pull_request" ]] 
          then
            echo "Pull from PR event"
            echo "::set-output name=commit_sha::${{ github.event.pull_request.merge_commit_sha }}"
          else
            echo "Pull from manual trigger parameter."
            echo "::set-output name=commit_sha::${{ github.event.inputs.commit_sha }}"
          fi
  create_release:
    runs-on: ubuntu-latest
    needs: get_commit_sha
    steps:
    - name: Echo commit sha
      run: echo ${{ needs.get_commit_sha.outputs.commit_sha }}
    - name: Checkout commit for release
      uses: actions/checkout@v2
      with:
        ref: ${{ needs.get_commit_sha.outputs.commit_sha }}
        fetch-depth: 0
    - name: Get version and change log
      id: get_version_and_changelog
      run: |
        version_name=$(cat gradle.properties | grep VERSION_NAME | sed  s/VERSION_NAME=//g)
        start_line_change_log=$(grep -n $version_name CHANGELOG.md | cut -f1 -d:)
        total_lines=$(cat CHANGELOG.md | wc -l)
        release_notes=$(sed -n "$start_line_change_log,$total_lines p" CHANGELOG.md)
        echo "::set-output name=version_name::$version_name"
        echo "::set-output name=release_notes::$release_notes"
        echo $version_name
        echo $release_notes
    - name: Create Github release
      uses: actions/github-script@v3
      env:
        RELEASE_NOTES: ${{ steps.get_version_and_changelog.release_notes }}
        VERSION_NAME: ${{ steps.get_version_and_changelog.version_name }}
        COMMIT_SHA: ${{ needs.get_commit_sha.outputs.commit_sha }}
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const { VERSION_NAME, RELEASE_NOTES, COMMIT_SHA } = process.env
          github.repos.createRelease({ 
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: `Release ${VERSION_NAME}`,
            tag_name: `release_v${VERSION_NAME}`,
            target_commitish: `${COMMIT_SHA}`,
            body: `${RELEASE_NOTES}`
          })
      
      
      
