name: Create a Github release
on:
  workflow_dispatch:
    commit_sha:
        description: 'The release commit'     
        required: true
env:
  GIT_USER_NAME: amplify-android-dev+ghops
  GIT_USER_EMAIL: amplify-android-dev+ghops@amazon.com
  COMMIT_SHA: ${{ github.event_name == 'pull_request' ? github.event.pull_request.merge_commit_sha : github.event.inputs.commit_sha }}
jobs:      
  create_release:
    runs-on: ubuntu-latest
    steps:
    - name: Echo commit env var
      run: echo $COMMIT_SHA
      
