name: Release-related workflows

on:
  push:
    branches: [ main ]

jobs:
  add_to_next_release:
    runs-on: ubuntu-latest
    steps:
    - name: Update git
      run: |
        sudo add-apt-repository -y ppa:git-core/ppa
        sudo apt-get update
        sudo apt-get install git -y
    - uses: actions/checkout@v2
      with:
        path: amplify-android
        ref: rjuliano/rel-workflow
        token: ${{ github.token }}
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install semantic-release and plugins
      run: |
        npm install -g semantic-release
        npm install -g @semantic-release/changelog
        npm install -g @semantic-release/git
        npm install -g @semantic-release/github
        npm install -g @semantic-release/exec
        npm install -g gradle-semantic-release-plugin
    - name: Merge changes from main
      run: |
        cd $GITHUB_WORKSPACE/amplify-android
        git fetch --tags
        git status
        git merge origin/main
