name: Update release branch
on:
  push:
    branches:
      - main
      - releases/next
jobs:
  update_release_branch:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install semantic-release and plugins
      run: |
        npm install -g semantic-release
        npm install -g @semantic-release/changelog
        npm install -g @semantic-release/git
        npm install -g @semantic-release/github
        npm install -g @semantic-release/exec
    - name: Update git
      run: |
        sudo add-apt-repository -y ppa:git-core/ppa
        sudo apt-get update
        sudo apt-get install git -y
    - uses: actions/checkout@v2
      with:
        ref: releases/next
        token: ${{ github.token }}
        fetch-depth: 0
    - name: Merge changes from main
      run: |
        cd $GITHUB_WORKSPACE
        git fetch --tags
        git status
        git merge origin/main
        git push origin releases/next
    - name: Release
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release
    - name: Manage PR for next release
      uses: repo-sync/pull-request@v2
      with:
        source_branch: releases/next
        destination_branch: main
        pr_title: Next release
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_allow_empty: true

      
        
