name: Update release branch
on:
  push:
    branches:
      - main
      - releases/next
jobs:
  update_release_branch:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Dump GitHub context ${{ github.job }}
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Update git
      run: |
        sudo add-apt-repository -y ppa:git-core/ppa
        sudo apt-get update
        sudo apt-get install git -y
    - uses: actions/checkout@v2
      with:
        ref: releases/next
        token: ${{ github.token }}
        fetch-depth: 0
    - name: Merge changes from main
      run: |
        cd $GITHUB_WORKSPACE
        git fetch --tags
        git status
        git merge origin/main
        git push origin releases/next
    - name: Manage PR for next release
      uses: repo-sync/pull-request@v2
      with:
        source_branch: releases/next
        destination_branch: main
        pr_title: Next release
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_allow_empty: true

      
        
