name: Commits pushed to main
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      name:
        description: 'test param description'
        required: true
        default: 'default value'
    
jobs:
  update_release_branch:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Update git
      run: |
        sudo add-apt-repository -y ppa:git-core/ppa
        sudo apt-get update
        sudo apt-get install git -y
    - uses: actions/checkout@v2
      with:
        ref: releases/next
        token: ${{ secrets.RELEASE_MANAGER_TOKEN }}
        fetch-depth: 0
    - name: Merge changes from main
      run: |
        cd $GITHUB_WORKSPACE
        git fetch --tags
        git status
        git rebase origin/main
        git push origin releases/next

      
        
