name: Update release branch
on:
  push
jobs:
  update_release_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context ${{ github.job }}
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
