name: Manage next release
on:
  push:
    branches:
      - releases/next
jobs:
  manage_release_pr:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/releases/next'
    steps:
    - uses: actions/checkout@v2
      with:
        ref: releases/next
        token: ${{ secrets.RELEASE_MANAGER_TOKEN }}
        fetch-depth: 0
    - name: Update git
      run: |
        sudo add-apt-repository -y ppa:git-core/ppa
        sudo apt-get update
        sudo apt-get install git -y
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install semantic-release and plugins
      run: |
        npm install -g semantic-release
        npm install -g @semantic-release/changelog
        npm install -g @semantic-release/git
        npm install -g @semantic-release/github
        npm install -g @semantic-release/exec
        npm install -g conventional-changelog-conventionalcommits
    - name: Update version
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_MANAGER_TOKEN }}
      run: | 
        ls -al
        npx semantic-release
        git status
        cat gradle.properties
        cat CHANGELOG.md
    - name: Manage PR for next release
      uses: repo-sync/pull-request@v2
      with:
        source_branch: releases/next
        destination_branch: main
        pr_title: Next release
        github_token: ${{ secrets.RELEASE_MANAGER_TOKEN }}
        pr_allow_empty: true

      
        
