name: Create PR for a release
on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Release from which branch?'
        required: true
        default: 'main'
jobs:
  create_pr_for_next_release:
    runs-on: ubuntu-latest
    steps:
    - name: Update git
      run: |
        sudo add-apt-repository -y ppa:git-core/ppa
        sudo apt-get update
        sudo apt-get install git -y
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.base_branch }}
        token: ${{ github.token }} # This will need to change to a token belonging to a service account.
        fetch-depth: 0
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Create or pull branch for the release
      run: |
        git checkout -b releases/`date "+%Y%m%d"`
        git pull origin releases/`date "+%Y%m%d"`
    - name: Install dependencies
      run: |
        cd scripts
        gem install bundler
        bundle install
    - name: Create PR for next release
      run: |
        cd scripts
        bundle exec fastlane android manage_next_release_pr
    - name: Check modified file content
      run: |
        cat gradle.properties
        cat CHANGELOG.md
        git status
